title: G. Curt Fulwider
description: Data & Learning scientist building interactive, data-driven systems for assessment, motivation, and student growth.
url: https://curtfulwider.com
markdown: kramdown
permalink: pretty
plugins: []
